/**
 * ZIP → County FIPS lookup.
 *
 * Loads from data/fips-data.json if available (generated by scripts/build-fips.ts),
 * otherwise falls back to an embedded subset for common metros.
 *
 * To generate full dataset (~42K entries):
 *   npx tsx scripts/build-fips.ts
 */

import type { FipsEntry } from "@dealscope/core";

// Try to load the full dataset; fall back to embedded subset
let FIPS_DATA: Record<string, FipsEntry>;

try {
  // Generated file — run `npx tsx scripts/build-fips.ts` to create
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  FIPS_DATA = require("../data/fips-data.json");
} catch {
  // Embedded fallback — covers major metros for development
  FIPS_DATA = {
    // Ohio
    "45406": { stateFips: "39", countyFips: "39113", countyName: "Montgomery", stateAbbr: "OH" },
    "45409": { stateFips: "39", countyFips: "39113", countyName: "Montgomery", stateAbbr: "OH" },
    "43215": { stateFips: "39", countyFips: "39049", countyName: "Franklin", stateAbbr: "OH" },
    "44113": { stateFips: "39", countyFips: "39035", countyName: "Cuyahoga", stateAbbr: "OH" },
    "45202": { stateFips: "39", countyFips: "39061", countyName: "Hamilton", stateAbbr: "OH" },
    // New York
    "10001": { stateFips: "36", countyFips: "36061", countyName: "New York", stateAbbr: "NY" },
    "10013": { stateFips: "36", countyFips: "36061", countyName: "New York", stateAbbr: "NY" },
    "11201": { stateFips: "36", countyFips: "36047", countyName: "Kings", stateAbbr: "NY" },
    "14202": { stateFips: "36", countyFips: "36029", countyName: "Erie", stateAbbr: "NY" },
    // California
    "90001": { stateFips: "06", countyFips: "06037", countyName: "Los Angeles", stateAbbr: "CA" },
    "90210": { stateFips: "06", countyFips: "06037", countyName: "Los Angeles", stateAbbr: "CA" },
    "94102": { stateFips: "06", countyFips: "06075", countyName: "San Francisco", stateAbbr: "CA" },
    "92101": { stateFips: "06", countyFips: "06073", countyName: "San Diego", stateAbbr: "CA" },
    "95814": { stateFips: "06", countyFips: "06067", countyName: "Sacramento", stateAbbr: "CA" },
    // Texas
    "77001": { stateFips: "48", countyFips: "48201", countyName: "Harris", stateAbbr: "TX" },
    "75201": { stateFips: "48", countyFips: "48113", countyName: "Dallas", stateAbbr: "TX" },
    "78201": { stateFips: "48", countyFips: "48029", countyName: "Bexar", stateAbbr: "TX" },
    "73301": { stateFips: "48", countyFips: "48453", countyName: "Travis", stateAbbr: "TX" },
    // Florida
    "33101": { stateFips: "12", countyFips: "12086", countyName: "Miami-Dade", stateAbbr: "FL" },
    "32801": { stateFips: "12", countyFips: "12095", countyName: "Orange", stateAbbr: "FL" },
    "33602": { stateFips: "12", countyFips: "12057", countyName: "Hillsborough", stateAbbr: "FL" },
    "32202": { stateFips: "12", countyFips: "12031", countyName: "Duval", stateAbbr: "FL" },
    // Illinois
    "60601": { stateFips: "17", countyFips: "17031", countyName: "Cook", stateAbbr: "IL" },
    "60602": { stateFips: "17", countyFips: "17031", countyName: "Cook", stateAbbr: "IL" },
    // Pennsylvania
    "19101": { stateFips: "42", countyFips: "42101", countyName: "Philadelphia", stateAbbr: "PA" },
    "15201": { stateFips: "42", countyFips: "42003", countyName: "Allegheny", stateAbbr: "PA" },
    // Georgia
    "30301": { stateFips: "13", countyFips: "13121", countyName: "Fulton", stateAbbr: "GA" },
    // Michigan
    "48201": { stateFips: "26", countyFips: "26163", countyName: "Wayne", stateAbbr: "MI" },
    // Massachusetts
    "02101": { stateFips: "25", countyFips: "25025", countyName: "Suffolk", stateAbbr: "MA" },
    // Arizona
    "85001": { stateFips: "04", countyFips: "04013", countyName: "Maricopa", stateAbbr: "AZ" },
    // Washington
    "98101": { stateFips: "53", countyFips: "53033", countyName: "King", stateAbbr: "WA" },
    // Colorado
    "80201": { stateFips: "08", countyFips: "08031", countyName: "Denver", stateAbbr: "CO" },
    // Tennessee
    "37201": { stateFips: "47", countyFips: "47037", countyName: "Davidson", stateAbbr: "TN" },
    // Indiana
    "46201": { stateFips: "18", countyFips: "18097", countyName: "Marion", stateAbbr: "IN" },
    // North Carolina
    "28201": { stateFips: "37", countyFips: "37119", countyName: "Mecklenburg", stateAbbr: "NC" },
    // Missouri
    "63101": { stateFips: "29", countyFips: "29510", countyName: "St. Louis City", stateAbbr: "MO" },
    "64101": { stateFips: "29", countyFips: "29095", countyName: "Jackson", stateAbbr: "MO" },
  };
}

/**
 * Look up county FIPS information from a ZIP code.
 * Returns null if ZIP is not in the dataset.
 */
export function lookupFips(zip: string): FipsEntry | null {
  return FIPS_DATA[zip] ?? null;
}

/**
 * Get the full 5-digit county FIPS code (state + county) for BLS queries.
 */
export function getCountyFips(zip: string): string | null {
  const entry = lookupFips(zip);
  return entry?.countyFips ?? null;
}

/**
 * Get the number of ZIP codes in the loaded dataset.
 */
export function getFipsCount(): number {
  return Object.keys(FIPS_DATA).length;
}
